### ISSUE TITLE
migrate package to null safety

### ISSUE THREAD

**Issue by Ritsz123** [Milad-Akarie/form_field_validator#9]
After flutter 2.0 update every package needs to be migrated to null safety.

**Comment by Ethirallan** [comment]
I posted PR #11. Until it is merged, you can add plugin like this:
```
  form_field_validator:
    git:
      url: https://github.com/Ethirallan/form_field_validator.git
      ref: master
```
